language: php

php:
  - 5.5.9
  - 5.6
  #- 7.0
  - hhvm

# optionally set up exclusions and allowed failures in the matrix
matrix:
  exclude:
    - php: 5.6
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  
script:
  - mkdir -p build/logs
  - phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
  
# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#poing"